### ISSUE TITLE
Error on Webpack while building

### ISSUE THREAD

**Issue by abhishekkprabhakar** [appcelerator/titanium-vue-sample#1]
Hello, I'm getting an error while building my first Vue project using Ti. 
I installed all prerequisites from https://github.com/appcelerator/titanium-vue
 
`
[INFO]  Running initial Webpack build
PATH-TO\titanium-vue-sample\app\node_modules\.bin\webpack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
[ERROR] An error occurred during build after 4s 385ms
[ERROR] Webpack exited with non-zero exit code 1
`

**Comment by janvennemann** [comment]
Hi, can you give some details about your environment? OS, versions of Node, appc-cli and Titanium SDK would be really helpful. Thanks!

**Comment by hansemannn** [comment]
@abhishekkprabhakar Any update here?

**Comment by janvennemann** [comment]
Closing due to no feedback.
